### ISSUE TITLE
Adapter. ToFullDictionary()

### ISSUE THREAD

**Issue by okedoki** [nreco/data#1]
I have found that to extract full dataset you have to implement POCO model, whereas ToDictionary() returns headers only.
Could you provide a method to extract all dataset to Dictionary? I made something by myself, but I'm not sure it is well written and done according to .NET core.

            public Dictionary<string, List<object>> ToFullDictionary()
            {
                System.Collections.Concurrent.ConcurrentDictionary<string, List<object>> results = new System.Collections.Concurrent.ConcurrentDictionary<string, List<Object>>();
                
                 DataHelper.ExecuteReader(SelectCommand, CommandBehavior.Default, DataReaderRecordOffset, Query.RecordCount,
                    (rdr) => {
                        Dictionary<string, object> dictionary = ReadDictionary(rdr);
                        foreach (KeyValuePair<string, object> entry in dictionary)
                        {
                            if (!results.ContainsKey(entry.Key))
                                results[entry.Key] = new List<object>();
                            results[entry.Key].Add(entry.Value);
                        }
                    });
                return results.ToDictionary(dict => dict.Key, dict => dict.Value); ;
            }

**Comment by VitaliyMF** [comment]
@okedoki ToDictionary returns first record returned by select query. If you need to load _all_ records, why not use ToList<Dictionary<string,object>>() ? Or you need to load exactly dictionary with column name => record values?

**Comment by okedoki** [comment]
@VitaliyMF 
Indeed, thank you. Can  you explain how can I manage other operations in the same way, namely Create, Update and Delete? 

One thing. I still believe it can be useful to have a dictionary  with ID as key over all records. 
The reason for that, we will have O(1) complexity to select from the list, comparing to O(n) for the unsorted list.

**Comment by VitaliyMF** [comment]
@okedoki  DbDataAdapter implements Insert, Update and Delete methods; Insert and Update can accept either POCO-model or Dictionary<string,object> (delete just needs a condition) -- see also [DataAdapter demo](https://github.com/nreco/data/blob/master/examples/SqliteDemo.DataAdapter/Program.cs).

regarding 

>  I still believe it can be useful to have a dictionary with ID as key over all records.
> The reason for that, we will have O(1) complexity to select from the list, comparing to O(n) for the unsorted list. 

it seems there is some misunderstanding here; could you provide me more information about your needs? 
ToList&lt;Dictionary&lt;string,object&gt;&gt; returns list of dictionaries so you can iterate through them and access record values by column name; each record represented by dictionary and column value is accessed with O(1). 

I assume that in some scenarios (for large amount of records) using dictionary per record might be unacceptable;  since DataTable/DataRow is not available in .NET Core, I already thought about special structure (smth like RecordSet) that will provide some simple interface for accessing record values.

**Comment by okedoki** [comment]
@VitaliyMF 

Problem is I don't see a way to do it. In that demo all Insert and update operations are done with the class model. I would like to do the following

```
1) IEnumerable<KeyValuePair<string, object>> dataDictionary= dbAdapter.Select(query).ToList<Dictionary<string, object>>()
2) dbAdapter.Update(query, dataDictionary)
3) dbAdapter.Insert(query, dataDictionary)
```

I think it would be useful for everyone to add the instructions to "How to use".

About 

>  I still believe it can be useful to have a dictionary with ID as key over all records.
> The reason for that, we will have O(1) complexity to select from the list, comparing to O(n) for the unsorted list.

It is not an issue anymore, but let me explain it.

If we have a big dataset(10^6 rows  ) with only tree columns ID, FirstName, SecondName and store it as a List<Dictionary<string, object>> than complexity to select  FirstName is O(N = 10^6) + O(1).
on the other hand if we had Dictionary<string, List<object>>, where key is an ID the complexity to select the same element(without consideration of collisions) is O(1) + O(M = 3).

Just to mention it can be much more efficient for specific kinds of tables.

**Comment by VitaliyMF** [comment]
@okedoki regarding insert / update.
`dbAdapter.Select(query).ToList<Dictionary<string, object>>()`  actually returns `List<Dictionary<string,object>>`.  dbAdapter.Update / dbAdapter.Insert are methods for ONE record -- this means that if you have to update several records, you need to call Insert or Update method for concrete `Dictionary<string,object>` instance in the cycle. DbDataAdapter knows nothing about your records and cannot just update list of dictionaries; but  I can add more overloads for mass insert/updates, for example:

`dbAdapter.Update(string idField, IEnumerable<IDictionary<string,object>> recordsToUpdate);
dbAdapter.Insert(string tableName, IEnumerable<IDictionary<string,object>> recordsToInsert);`

does it make sense for you? If yes please let me know, and I'll include these changes into upcoming 1.0-alpha4 .

> I think it would be useful for everyone to add the instructions to "How to use".

got that, I will add more examples / how to use code snippets on occasion (if you want to help with that, you're welcome).

regarding:

> Just to mention it can be much more efficient for specific kinds of tables.

it seems you need to load many records into memory and access them very fast with hashmap by some fields. I don't think that this should be handled on the data layer API - after all, you always can do that in most efficient way by executing data reader (by command generated by DbCommandBuilder) and building hashmaps 'some field' -> 'records list' (or ids list) that needed exactly for your task.

By the way, here are list of possible features for 1.0 release: [Roadmap](https://github.com/nreco/data/wiki/Roadmap). If some of them look useful for you just let me know.

**Comment by okedoki** [comment]
@VitaliyMF 

Thank you for the detailed explanation. 

I would be happy to participate in the development of the library. 

> but I can add more overloads for mass insert/updates, for example.
I think it would be useful feature for everyone who use this library, but personally I have different plans for usage.

After a discussion with my colleagues we focus on  a possibility to work on a lower level(directly with the commands) and particularly we are interested in a possibility of batches. 
I think you have a class for it, so I will try to figure out.

> DbBatchCommandGenerator: generate SQL statements in a batch (one DbCommand for several statements)
