### ISSUE TITLE
Does this library handle sending a UDT as a stored procedure parameter?

### ISSUE THREAD

**Issue by SpilledMilkCOM** [nreco/data#14]
I was curious if you have an abstraction for stored procedures, specifically sending in User Defined Table Types as parameters.  The old "ToDataTable" method in the old .Net extensions doesn't work and I'm trying to send something to the stored procedure as a SqlDbType.Structured parameter.  The extensions used to convert a List<> to a DataTable and that could be sent to the stored procedure.  I'm using the FromSql() method for other stored procedure calls rather successfully, but now things are bogged down by this.  THANKS!

**Comment by VitaliyMF** [comment]
@SpilledMilkCOM Have you tried to pass DbDataReader implementation (say, RecordSetReader) as TVP value? Something like that:

```
SqlCommand sqlCmd; // command to execute stored procedure with TVP
var rs = new RecordSet(
	new[] {
		new RecordSet.Column("id", typeof(int)),
		new RecordSet.Column("name", typeof(string)),
	}
);
rs.Add(new[] { 1, "Test" });
var tvpParam = new SqlParameter("paramName", new RecordSetReader(rs) );
tvpParam.SqlDbType = SqlDbType.Structured;
sqlCmd.Parameters.Add( tvpParam );
```

If this doesn't work, another alternative might be passing TVP as `IEnumerable<DbDataRecord>` (for this purpose, I can add new method to RecordSet class, something like RecordSet.AsDataRecords() ).

**Comment by SpilledMilkCOM** [comment]
That looks like that worked!!  I used FromSql() however, do you want me to post that sample?  Or email it to you?  I think if you have samples with FromSql() more people might be using this library.  So far so good.  My initial trial was with a single column UDT.  I will extend it, but I'm sure it will work.  THANKS AGAIN!!  (you can delete this post, I felt it was the quickest way to get back with you)

**Comment by VitaliyMF** [comment]
@SpilledMilkCOM you're welcome to post your sample code here (in this case I'll move it to wiki page  https://github.com/nreco/data/wiki/RecordSet ).

As I understand at this moment you use EF Core FromSql method to invoke your stored procedure. As alternative, I can add DbDataAdapter.Select method overload that accepts the same arguments as 'FromSql'; as result you'll able to map results to POCO models (or to RecordSet structure) without EF core at all. What do you think about this enhancement?

**Comment by SpilledMilkCOM** [comment]
I would like to stay with EF Core for now since we are evaluating it and may not go with it right off the bat.  I will clean up what I have and then post it.

**Comment by SpilledMilkCOM** [comment]
I tried to clean up the classes as much as possible and reduce the noise.  So far I'm pretty happy with what I have.  The classes in my reflection namespace DON'T know about RecordSet and that's intentional.  If I move the SqlParameter methods, they will move to a NCM.DataModels.Common (or something like that).  So my DbContext is the only class that knows about NReco.Data.

I didn't see anything in your RecordSet constructor that takes an attributed list.  I think ideally if I could construct a RecordSet (or generic RecordSet) that took a list as a parameter and do the appropriate thing to build out the RS.  The TType class would be attributed appropriately.  Then all I would have to do is...

private RecordSetReader ConstructUDTValues<TType>(List<TType> valueList)
{
	var valueRecordSet = new RecordSet<TType>(valueList);
	
	return new RecordSetReader(valueRecordSet);
}
[GitHub sample.txt](https://github.com/nreco/data/files/475777/GitHub.sample.txt)
[GitHub sample.txt](https://github.com/nreco/data/files/475779/GitHub.sample.txt)



I wish I could work with you on setting this up, but hopefully there is enough here for you.  I hope that my reflection code works for you, but maybe you have your own.  I don't know any other way to contact you, other than through here.

**Comment by SpilledMilkCOM** [comment]
I tried to clean up the classes as much as possible and reduce the noise.  So far I'm pretty happy with what I have.  The classes in my reflection namespace DON'T know about RecordSet and that's intentional.  If I move the SqlParameter methods, they will move to a NCM.DataModels.Common (or something like that).  So my DbContext is the only class that knows about NReco.Data.

I didn't see anything in your RecordSet constructor that takes an attributed list.  I think ideally if I could construct a RecordSet (or generic RecordSet) that took a list as a parameter and do the appropriate thing to build out the RS.  The TType class would be attributed appropriately.  Then all I would have to do is...

private RecordSetReader ConstructUDTValues<TType>(List<TType> valueList)
{
	var valueRecordSet = new RecordSet<TType>(valueList);
	
	return new RecordSetReader(valueRecordSet);
}

I wish I could work with you on setting this up, but hopefully there is enough here for you.  I hope that my reflection code works for you, but maybe you have your own.  I don't know any other way to contact you, other than through here.

[GitHub sample.txt](https://github.com/nreco/data/files/475780/GitHub.sample.txt)

**Comment by SpilledMilkCOM** [comment]
The generic parameters didn't show up in my comments above, but they are in the attached file.  Hope this helps!!

**Comment by VitaliyMF** [comment]
@SpilledMilkCOM thanks a lot for your contribution. 
I've added sample code snipped for using RecordSet as TVP for EF Core FromSql here: https://github.com/nreco/data/wiki/RecordSet

TVP construction utility from RecordSet or list of POCO models moved to #16
