### ISSUE TITLE
Working example for mvc+react+EF+nreco.data

### ISSUE THREAD

**Issue by MakaBuka** [nreco/data#21]
Hi guys,

It seems that we don't have example which is based on NReco.Data.

Let's try to develop it by using next stack:

- mvc (.net core/api)
- react (or angular 2, we should mull it over and decide what we will use for our example)
- EF - CodeFirst and migration
- NReco.Data - to provide data from database

Please, confirm these steps.

Thx, D.

**Comment by VitaliyMF** [comment]
Good idea, it is typical case when EF Core is used in combination with NReco.Data for performance-critical queries (or just dynamic queries, stored procedure queries).

Don't spend much time on the UI, this example should illustrate how to use EF Core context for NReco.Data components initialization with DI.

**Comment by VitaliyMF** [comment]
Done by @MakaBuka
