### ISSUE TITLE
How to have binary data in your POCO?

### ISSUE THREAD

**Issue by gustavjon** [nreco/data#24]
I could use some help inserting binary data.

The database I'm using is sql server 2014. The column i'm trying to insert som bytes into looks like this:

[BinaryData][varbinary](max) NULL,

In my code the  property  looks like this:

 public byte?[] BinaryData { get; set; }

I'm simply inserting this using

dbAdapter.Insert("MyTable", entity);

but when It's inserted I get this exception "Implicit conversion from data type nvarchar to varbinary(max) is not allowed". 

If I comment out the binary property everything works just fine. 

I've tried adding the Column annotation like this on the property in my code but that didnt help.

[Column(“BinaryData", TypeName="varbinary")]

Some help would be much appreciated.

**Comment by VitaliyMF** [comment]
@gustavjon I may assume that problem in the "byte?[]" type - it is not detected as known type for varbinary sql type. Could you try "byte[]" and let me know about the results?

**Comment by VitaliyMF** [comment]
@gustavjon is your question is still actual? Could you provide any update?

**Comment by gustavjon** [comment]
I tried byte[] but I had the same problem. I decided to write a stored procedure instead but I actually ran into the same error doing that when I tried to insert null so in the end I had to make the column default to null rather then inserting a null value.

**Comment by VitaliyMF** [comment]
@gustavjon I've performed some tests with SQL server and "varbinary" column type and found the following:

- when model has "byte[]" property with null value, suggested parameter type is varchar and this causes convert issue (unit tests use SQLite and it works without any errors in this case). Resolution should be setting DbParameter type explicitly if parameter value is null
- when model has "byte[]" property with binary data, it is incorrectly passed as parameter.

Thank you for reporting about the issue! I'll try to provide bugfix release soon.

**Comment by VitaliyMF** [comment]
Shipped in 1.0.1
