### ISSUE TITLE
Any way to obtain metadata?

### ISSUE THREAD

**Issue by leak** [nreco/data#25]
Is there any way to obtain data source metadata?

Tables, Columns, Column Types, etc.

**Comment by VitaliyMF** [comment]
@leak you can read query results to [RecordSet](https://github.com/nreco/data/blob/master/src/NReco.Data/RecordSet.cs) and it will be populated with some metadata automatically (columns and their data types). If data reader implements [IDbColumnSchemaGenerator](https://github.com/dotnet/corefx/blob/master/src/System.Data.Common/src/System/Data/Common/IDbColumnSchemaGenerator.cs) interface (this depends on the ADO.NET provider implementation), it will be used to get extra details (primary key, nullable, autoincrement).

Regarding list of table, ADO.NET doesn't provide standard interfaces for getting this information.  You can execute database-specific metadata query (like "exec sp_tables" for SQL Server), or use ANSI-standard information schema query like "SELECT table_name FROM information_schema.tables". Note that some databases does not support this way of getting database metadata (SQLite, Oracle).

**Comment by VitaliyMF** [comment]
I think it is good idea to add an example that illustrates how to get DB metadata by querying "information_schema" tables.

**Comment by VitaliyMF** [comment]
Added "DbMetadata" example (thanks to @MakaBuka!) that illustrates how to query information_schema views with NReco.Data ( https://github.com/nreco/data/tree/master/examples/MySqlDemo.DbMetadata ).

**Comment by leak** [comment]
Thanks alot for the illustration
