### ISSUE TITLE
table schema name

### ISSUE THREAD

**Issue by wendt88** [nreco/data#29]
Is it possible to select/update/insert on tables with custom schema name and how?
Can't find nothing about that

**Comment by VitaliyMF** [comment]
Implicit conversion between string and `QTable` that occurs in code like `new Query("contacts.c")` treats evertything after last '.' as table alias; this query is converted to the following SQL:
```
SELECT * FROM contacts c
```
If you don't want to specify table alias and want to specify table schema you can do that in the following way: `new Query( new QTable("myschema.contacts", null) )`

When schema-qualified name is specified in DbDataAdapter methods that accept table name as string nothing special is needed, for example:
```
DbAdapter.Insert("main.companies", new Dictionary<string,object>() {
	{"title", "Test Inc"},
	{"country", "Norway"},
	{"logo_image", null}
}) );
DbAdapter.Update("main.companies", companyRS);  // update recordset
```
Please note that there was a bug with handling schema-qualified name in Insert/Update/Delete methods that already fixed (don't forget to update to version 1.0.1 that was published today).
