### ISSUE TITLE
How to get multiple Recordsets from storedprocedure?

### ISSUE THREAD

**Issue by wendt88** [nreco/data#36]
Hi,
can you help me how to call a stored procedure, passing parameters (if possible also output parameters) which returns me multiple recordsets?
At the moment i call: `dbAdapter.Select($"STOREDNAME @{nameof(SQLPARAMETER)}", SQLPARAMETER).ToRecordSet()`
but there I have only the first one and also the output SQLPARAMETERS are null

**Comment by VitaliyMF** [comment]
See my answer on SO: http://stackoverflow.com/questions/42970640/how-to-get-multiple-recordsets-from-storedprocedure-with-nreco-data-in-asp-netco/42971606#42971606

I've added an issue for multiple resultsets support by DbDataAdapter: https://github.com/nreco/data/issues/35 (I guess this can be done very quickly, in a day or so).

**Comment by wendt88** [comment]
THX!

do you can help me also for the second problem on getting an outputvalue via sqlparameter?
you call:
```
declare @p4 nvarchar(4000)
exec sp_executesql N'STOREDNAME , @SQLPARAMETER',N'@SQLPARAMETER nvarchar(4000) output',@SQLPARAMETER=@p4
select @p4
```
so my SQLPARAMETER value is null.
This call works:
```
declare @p4 nvarchar(4000)
exec STOREDNAME @p4 out
SELECT @p4
```

**Comment by VitaliyMF** [comment]
@wendt88  it seems you need to compose `SqlCommand` by yourself, and specify `SqlParameter` as 'output':

```
SqlCommand cmd;  
var p = new SqlParameter();
p.ParameterName = "@p1";
p.DbType = DbType.Int32;
p.Direction = ParameterDirection.Output;
cmd.Parameters.Add(p);
```
and after c`md.ExecuteNonQuery ` you'll get output parameter value in `p.Value`.

This is standard ADO.NET API, and it seems NReco.Data cannot add anything really valuable exactly for this case.

**Comment by wendt88** [comment]
thx, my problem was the missing line `command.CommandType = CommandType.StoredProcedure;`
it is possible to set on `SqlCommand`, but wasn't in my first code `dbAdapter.Select($"STOREDNAME @{nameof(SQLPARAMETER)}", SQLPARAMETER)`

**Comment by VitaliyMF** [comment]
@wendt88   `CommandType.StoredProcedure` is used only if CommandText contains just procedure name, isn't it? And you can call any stored procedure with `CommandType.Text` with help of 'exec STOREDNAME @p0, @p1', for example:
```
dbAdapter.Select("execute STOREDNAME {0}", SQLPARAMETER)
```

Maybe I've missed something?..

**Comment by wendt88** [comment]
Thats right!
Now i have to make a workaround for getting more recordsets like http://stackoverflow.com/questions/42970640/how-to-get-multiple-recordsets-from-storedprocedure-with-nreco-data-in-asp-netco/42971606#42971606
So the problem is solved at the moment
