### ISSUE TITLE
Get details using SQL Stored Procedure in Nreco.data, .net core c#

### ISSUE THREAD

**Issue by netpand** [nreco/data#40]
How to get result table using SQL stored procedures with parameter values in  NReco.Data.DbDataAdapter 
.Net core

**Comment by VitaliyMF** [comment]
You can use [DbDataAdapter.Select(string sql, params Object[] parameters)](https://www.nrecosite.com/doc/NReco.Data/?topic=html/M_NReco_Data_DbDataAdapter_Select_2.htm) to execute stored procedures and map results to POCO or RecordSet.

**Comment by netpand** [comment]
Thank you for your answer!

I can able to get the RecordSet ,

**Comment by netpand** [comment]
Thank you for your answer!
I can get the RecordSet.

Now I can't able to Insert/Update table using stored procedure.
below is my code

var jobCreate = dbAdapter.Select("execute MYSTOREDPROCEDURE {0},{1},{2},{3},{4},{5},{5},{7}", null, null, 101, null, null, DateTime.Now, null, null);

AND

var jobCreate = dbAdapter.Insert("execute MYSTOREDPROCEDURE {0},{1},{2},{3},{4},{5},{5},{7}", null, null, 101, null, null, DateTime.Now, null, null);

**Comment by VitaliyMF** [comment]
@netpand when you use stored procedure NReco.Data doesn't know what it does - so any stored procedure can be executed with "Select" method. If SP that performs inserts/updates doesn't return anything so you will get empty result with ".ToRecordSet()".

Semantically it is a bit weird when SP for insert/update is executed with "Select" method so I can add one more method, say "Execute" that has the same signature as "Select(string,params object[])" but doesn't return any results. Let me know if this is exactly what you need.

**Comment by netpand** [comment]
Thanks for quick response. 
Issue got resolved.The problem from our end.
