### ISSUE TITLE
Please make lowercase keys in ColNamMap dictionary

### ISSUE THREAD

**Issue by fedkov** [nreco/data#43]
https://github.com/nreco/data/blob/59a0cba666a009f7bf4ef28edb6cb4d238309201/src/NReco.Data/DataMapper.cs#L160
https://github.com/nreco/data/blob/59a0cba666a009f7bf4ef28edb6cb4d238309201/src/NReco.Data/DataMapper.cs#L172
Mapper doesn't work when column and POCO property are in different case (For example: item_id and Item_ID)

**Comment by VitaliyMF** [comment]
That's correct, in case if column and property are different:

- use [Column("item_id")] data annotation attr to specify column name (like for EF)
- or use DbDataAdapter.Select(..).SetMapper(customMapHandler).ToList<Model>()  to specify custom mapping logic
