### ISSUE TITLE
Insert operation fails when executing in Transaction

### ISSUE THREAD

**Issue by s-vitalii** [nreco/data#48]
Insert operation works perfect without Transaction, however it is failing inside Transaction.
Since, TransactionScope is not working in NetCore 2, I was manually opened transaction using BeginTransaction method in Connection.
Example:

> var isClosedConn = dbDataAdapter.Connection.State == ConnectionState.Closed;
			if (isClosedConn)
				dbDataAdapter.Connection.Open();
using (var tr = dbDataAdapter.Connection.BeginTransaction()) {
				try {
					dbDataAdapter.Transaction = tr;
					var insertedCount = dbDataAdapter.InsertAsync(newAcc).Result;
					tr.Commit();
				} catch (Exception ex) {
					tr.Rollback();
				}
				finally {
					if (isClosedConn)
						dbDataAdapter.Connection.Close();
					dbDataAdapter.Transaction = null;
				}

After main insert operation and if you have autoincrement column in your POCO model, additional select is executing to get last inserted id and failing because transaction was not injected to that command.

**Comment by fedkov** [comment]
Problem can be fixed by adding transaction parameter and initializing Transaction property of internal IDbCommand used in GetInsertId/GetInsertIdAsync methods

`		/// <summary>
		/// Gets ID of last inserted record
		/// </summary>
		object GetInsertId(IDbConnection connection, IDbTransaction transaction = null);

		/// <summary>
		/// Asynchronously gets ID of last inserted record
		/// </summary>
		Task<object> GetInsertIdAsync(IDbConnection connection, CancellationToken cancel, IDbTransaction transaction = null);`

**Comment by VitaliyMF** [comment]
@fedkov yeah it seems this is only way to fix this. Unfortunately this requires changes in IDbFactory interface which is not good in terms of backward compatibility. Do you need this fix ASAP?

**Comment by fedkov** [comment]
@VitaliyMF not for now.
But when fixing this please consider also adding some configuration parameter to DbDataAdapper, which can enable DataMapper behavior mentioned #43.

**Comment by VitaliyMF** [comment]
@fedkov regarding #43 I've provided an answer what do if model properties doesn't match column names - I don't see any need to change anything in the library. If you have any questions let's continue the discussion about this in #43.

**Comment by VitaliyMF** [comment]
Shipped in 1.0.6
