### ISSUE TITLE
Add example for GraphQL subquery (nested query)

### ISSUE THREAD

**Issue by GOVYANSONG** [nreco/data#56]
The existing example does not currently demonstrate how to construct nested query. Any special consideration would be required to properly handle foreign key between tables? Does the library support pagination out of box?

**Comment by VitaliyMF** [comment]
SqliteDemo.GraphQLApi example just illustrates the capability, it doesn't implement anything else beyond simple table queries.

If you're looking for ready-to-use component that can handle:

- graphql schema to DB schema mapping configured with JSON
- nested queries
- load related objects
- filter parameters
- pagination

Take a look to [NReco.GraphQL library](https://www.nrecosite.com/graphql_to_sql_database.aspx) -- this is commercial product, but pricing is very reasonable.
