### ISSUE TITLE
Option "None" for attribute "DatabaseGenerated" was ignored

### ISSUE THREAD

**Issue by s-vitalii** [nreco/data#64]
NReco.Data doesn't process correctly option "None" for DatabaseGeneratedAttribute. 
Please check the following code snippet

> [Key]
[Column("id")]
[DatabaseGenerated(DatabaseGeneratedOption.None)]
    public int Id { get; set; }

This code is valid. However, during INSERT command column {Id} will be skipped because NReco.Data will think that column's value should be generated in DB but not manually. I assume that it checks existing of attribute "DatabaseGenerated" but not "None" option.

**Comment by VitaliyMF** [comment]
Shipped in 1.2.4
