### ISSUE TITLE
Please check this repo using SonarQube.

### ISSUE THREAD

**Issue by PolywickStudio** [nreco/data#66]
Please check this project using SonarQube.

I added this C# project on CI integration with SonarQube. Here's some (not all) of the QA analysis I get:

Nreco\src\NReco.Data\RecordSet.cs(536,10): warning CS1570: XML comment has badly formed XML -- 'End tag 'summary' does not match the start tag 'T'.' [Nreco\src\NReco.Data\NReco.Data.csproj]

Nreco\src\NReco.Data\RecordSet.cs(540,1): warning CS1570: XML comment has badly formed XML -- 'Expected an end tag for element 'summary'.' [Nreco\src\NReco.Data\NReco.Data.csproj]

Nreco\src\NReco.Data\Query\QConst.cs(23,15): warning CS0660: 'QConst' defines operator == or operator != but does not override Object.Equals(object o) [Nreco\src\NReco.Data\NReco.Data.csproj]

Nreco\src\NReco.Data\Query\QConst.cs(23,15): warning CS0661: 'QConst' defines operator == or operator != but does not override Object.GetHashCode() [Nreco\src\NReco.Data\NReco.Data.csproj]

Nreco\src\NReco.Data\Query\QField.cs(23,15): warning CS0660: 'QField' defines operator == or operator != but does not override Object.Equals(object o) [Nreco\src\NReco.Data\NReco.Data.csproj]

Nreco\src\NReco.Data\Query\QField.cs(23,15): warning CS0661: 'QField' defines operator == or operator != but does not override Object.GetHashCode() [Nreco\src\NReco.Data\NReco.Data.csproj]

Nreco\src\NReco.Data\DbBatchCommandBuilder.cs(39,10): warning CS1591: Missing XML comment for publicly visible type or member 'DbBatchCommandBuilder.DbBatchCommandBuilder(IDbFactory)' [Nreco\src\NReco.Data\NReco.Data.csproj]

Nreco\src\NReco.Data\DbBatchCommandBuilder.cs(43,15): warning CS1591: Missing XML comment for publicly visible type or member 'DbBatchCommandBuilder.BeginBatch()' [Nreco\src\NReco.Data\NReco.Data.csproj]

Nreco\src\NReco.Data\DbBatchCommandBuilder.cs(47,21): warning CS1591: Missing XML comment for publicly visible type or member 'DbBatchCommandBuilder.EndBatch()' [Nreco\src\NReco.Data\NReco.Data.csproj]

Nreco\src\NReco.Data\DbBatchCommandBuilder.cs(55,33): warning CS1591: Missing XML comment for publicly visible type or member 'DbBatchCommandBuilder.GetCommand()' [Nreco\src\NReco.Data\NReco.Data.csproj]

Nreco\src\NReco.Data\DbBatchCommandBuilder.cs(61,27): warning CS1591: Missing XML comment for publicly visible type or member 'DbBatchCommandBuilder.SetCommandText(IDbCommand, string)' [Nreco\src\NReco.Data\NReco.Data.csproj]

Nreco\src\NReco.Data\DbCommandBuilder.cs(121,35): warning CS1591: Missing XML comment for publicly visible type or member 'DbCommandBuilder.GetSqlBuilder(IDbCommand)' [Nreco\src\NReco.Data\NReco.Data.csproj]

Nreco\src\NReco.Data\DbCommandBuilder.cs(127,32): warning CS1591: Missing XML comment for publicly visible type or member 'DbCommandBuilder.GetCommand()' [Nreco\src\NReco.Data\NReco.Data.csproj]

Nreco\src\NReco.Data\DbCommandBuilder.cs(131,26): warning CS1591: Missing XML comment for publicly visible type or member 'DbCommandBuilder.SetCommandText(IDbCommand, string)'

**Comment by VitaliyMF** [comment]
All these warnings are not important.

**Comment by PolywickStudio** [comment]
If we fork, then fix can you merge ?
